[package]
name = "boojum"
version = "0.1.0"
edition = "2021"

[dependencies]
boojum = { path = "../repos/era-boojum", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
chrono = "0.4"
